name: E2E Tests

on:
  push:
    branches: [main]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Start Docker Compose services
        env:
          TAILSCALE_CLIENT_ID: ${{ secrets.TAILSCALE_CLIENT_ID }}
          TAILSCALE_CLIENT_SECRET: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          TAILSCALE_DOMAIN: ${{ secrets.TAILSCALE_DOMAIN }}
        run: docker compose up -d --wait

      - name: Run E2E tests
        env:
          TAILSCALE_DOMAIN: ${{ secrets.TAILSCALE_DOMAIN }}
        run: npm test

      - name: Show Docker logs on failure
        if: failure()
        run: docker compose logs --tail all

      - name: Stop and remove Docker Compose services
        if: always()
        run: docker compose down -v
